FROM quay.io/bitnami/sealed-secrets-controller:v0.13.1-739901134 as image1
FROM quay.io/calico/node:v3.17.3-20-gf056d14013cf as image2
FROM quay.io/calico/typha:v3.17.2-ppc64le as image3
FROM quay.io/thanos/thanos:v0.16.0-rc.0 as image4
FROM quay.io/calico/dikastes:v3.16.6 as image5
FROM quay.io/calico/gobgpd:v0.1.2 as image6
FROM quay.io/calico/felix:v3.2.1 as image7
