FROM quay.io/bitnami/sealed-secrets-controller:v0.15.0 as image1
FROM quay.io/calico/node:v3.17.3-20-gf056d14013cf as image2
FROM quay.io/calico/typha:v3.19.0 as image3
FROM quay.io/thanos/thanos:v0.20.1 as image4
FROM quay.io/calico/dikastes:v3.19.0 as image5
FROM quay.io/calico/gobgpd:v0.2.2-35-g8ea1e24-amd64 as image6
FROM quay.io/calico/felix:2.6.8 as image7
